[package]
name = "tidk"
version = "0.1.5"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2018"

[dependencies]
bio = "*"
rust-htslib = { version = "*", default-features = false }
clap = "~2.33.0"
rayon = "1.5.0"
# in explore::get_telomeric_repeat_estimates()
itertools = "0.10.0"
cmd_lib = "1.0.10"
# in utils::lms()
lexical-sort = "0.3.1"
# for plotting
csv = "1.1.5"
serde = "1.0.123"